conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, order_create, order_history_view

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('history/', order_history_view, name='history'),
    path('order/', order_create, name='order')
]

products/urls.py
from django.urls import path

from products.views import ProductsListView, ProductDetailView, add_or_remove, add_or_remove_likes, ProductCommentView

app_name = 'products'

urlpatterns = [
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/<int:pk>/', add_or_remove, name='add-or-remove'),
    path('comment/<int:pk>/', ProductCommentView.as_view(), name='comment'),
    path('likes/<int:pk>/', add_or_remove_likes, name='add-or-remove-likes'),
    path('', ProductsListView.as_view(), name='list'),
]

products/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _



class ProductCategoryModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product Category')
        verbose_name_plural = _('Product Categories')


class ProductTagModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product Tag')
        verbose_name_plural = _('Product Tags')


class ProductColorModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))
    code = models.CharField(max_length=7)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product Color')
        verbose_name_plural = _('Product Colors')


class ProductSizeModel(models.Model):
    name = models.CharField(max_length=128,verbose_name=_('name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product Size')
        verbose_name_plural = _('Product Sizes')


class ProductManufacture(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))
    logo = models.ImageField(null=True, blank=True, upload_to='manufacture/')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product Manufacture')
        verbose_name_plural = _('Product Manufactures')


class ProductModel(models.Model):
    image1 = models.ImageField(upload_to='products/')
    image2 = models.ImageField(upload_to='products/')

    name = models.CharField(max_length=255, verbose_name=_('name'))
    long_description = models.TextField(verbose_name=_('long_description'))
    short_description = models.CharField(max_length=255, verbose_name=_('short_description'))
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0,
                                                validators=
                                                [MaxValueValidator(100), MinValueValidator(0)]
                                                )
    sku = models.CharField(max_length=10, unique=True)
    count = models.PositiveIntegerField()
    real_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)

    manufacture = models.ForeignKey(ProductManufacture, on_delete=models.CASCADE, related_name='products')
    colors = models.ManyToManyField(ProductColorModel, related_name='products')
    tags = models.ManyToManyField(ProductTagModel, related_name='products')
    categories = models.ManyToManyField(ProductCategoryModel, related_name='products')
    sizes = models.ManyToManyField(ProductSizeModel, related_name='products')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def is_discount(self):
        return self.discount != 0

    def is_available(self):
        return self.count != 0

    def get_price(self):
        if self.is_discount():
            return self.price - self.discount * self.price / 100

    def get_related_products(self):
        return ProductModel.objects.filter(categories=1).exclude(pk=self.pk)[:3]

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')


class ProductImageModel(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name='images')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'image'
        verbose_name_plural = 'images'

UserModel = get_user_model()

class ProductCommentModel(models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='comments')
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

products/forms.py
from django import forms

from products.models import ProductCommentModel


class ProductCommentModelForm(forms.ModelForm):
    class Meta:
        model = ProductCommentModel
        fields = ['message']

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView

from products.forms import ProductCommentModelForm
from products.models import ProductModel, ProductCategoryModel, ProductColorModel, ProductTagModel, ProductManufacture, \
    ProductImageModel, ProductCommentModel


class ProductsListView(ListView):
    template_name = 'products/product-list.html'
    model = ProductModel
    context_object_name = 'products'

    @staticmethod
    def change_colors_structure():
        colors = ProductColorModel.objects.all()
        colors_list = []
        temp_colors = []

        for color in colors:
            temp_colors.append(color)
            if len(temp_colors) == 2:
                colors_list.append(temp_colors)
                temp_colors = []  # Reset temp_colors to a new list after appending

        # Append any remaining colors in temp_colors if it is not empty
        if temp_colors:
            colors_list.append(temp_colors)

        return colors_list

    def get_queryset(self):
        products = self.model.objects.all().order_by('-created_at')
        tag = self.request.GET.get('tag')
        cat = self.request.GET.get('cat')
        col = self.request.GET.get('col')
        man = self.request.GET.get('man')
        sort = self.request.GET.get('sort')
        q = self.request.GET.get('q')

        if tag:
            products = products.filter(tags__in=tag)
        if cat:
            products = products.filter(categories__in=cat)
        if col:
            products = products.filter(colors__in=col)
        if man:
            products = products.filter(manufacture__in=man)
        if sort:
            if sort == '-price':
                products = products.order_by('-real_price')
            else:
                products = products.order_by('real_price')
        if q:
            products = products.filter(name__icontains=q)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategoryModel.objects.all()
        context['manufactures'] = ProductManufacture.objects.all()
        context['tags'] = ProductTagModel.objects.all()
        context['colors'] = ProductColorModel.objects.all()
        return context


class ProductDetailView(DetailView):
    template_name = 'products/product-detail.html'
    model = ProductModel
    context_object_name = 'product'

    @staticmethod
    def change_colors_structure():
        colors = ProductColorModel.objects.all()
        colors_list = []
        temp_colors = []

        for color in colors:
            temp_colors.append(color)
            if len(temp_colors) == 2:
                colors_list.append(temp_colors)
                temp_colors = []  # Reset temp_colors to a new list after appending

        # Append any remaining colors in temp_colors if it is not empty
        if temp_colors:
            colors_list.append(temp_colors)

        return colors_list

    def get_context_data(self, *, object_list=None,  **kwargs):
        product = ProductModel.objects.get(id=self.kwargs["pk"])
        context = super().get_context_data(**kwargs)
        context.update({
            'comments': product.comments.all(),
            'products': ProductModel.objects.all(),
            'categories': ProductCategoryModel.objects.all(),
            'manufactures': ProductManufacture.objects.all(),
            'tags': ProductTagModel.objects.all(),
            'colors': ProductColorModel.objects.all()
        })
        return context


def add_or_remove(request, pk):
    cart = request.session.get('cart', [])
    if pk in cart:
        cart.remove(pk)

    else:
        cart.append(pk)

    request.session['cart'] = cart
    return redirect(request.GET.get('next', 'products:list'))


def add_or_remove_likes(request, pk):
    likes = request.session.get('likes', [])
    if pk in likes:
        likes.remove(pk)

    else:
        likes.append(pk)

    request.session['likes'] = likes
    return redirect(request.GET.get('nextt', 'products:list'))


class ProductCommentView(LoginRequiredMixin, CreateView):
    template_name = 'products/product-detail.html'
    form_class = ProductCommentModelForm
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        product_id = self.kwargs['pk']
        product = ProductModel.objects.get(pk=product_id)
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.product = product
        comment.save()
        return self.get_success_url()

    def form_invalid(self, form):
        return self.success_url()

    def get_success_url(self):
        return redirect(self.request.GET.get('next', 'products:list'))

templates/products/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div id="checkout" class="main-content">
        <div class="wrap-banner">
            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Checkout</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
			
            <!-- main -->
            <div id="wrapper-site">
                <div class="container">
                    <div class="row">
                        <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                            <div id="main">
                                <div class="cart-grid row">
                                    <div class="col-md-9 check-info">
                                        <div class="checkout-personal-step">
                                            <h3 class="step-title h3 info">
                                                <span class="step-number">1</span>PERSONAL INFORMATION
                                            </h3>
                                        </div>
                                        <div class="content">
                                            <ul class="nav nav-inline">
                                            </ul>
                                            <div class="tab-content">
                                                <div class="tab-pane fade in active show" id="checkout-guest-form" role="tabpanel">
                                                    <form action="{% url 'orders:order' %}" id="customer-form" class="js-customer-form" method="post">
                                                        {% csrf_token %}
                                                        <div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="address" type="text" placeholder="Address">
                                                            </div>
                                                            <div class="form-group row">
                                                                <input class="form-control" name="phone" type="text" placeholder="Phone">
                                                            </div>
                                                        </div>
                                                        <div class="clearfix">
                                                            <div class="row">
                                                                <input type="hidden" name="submitCreate" value="1">

                                                                <button class="continue btn btn-primary pull-xs-right" name="continue" data-link-action="register-new-customer" type="submit"
                                                                    value="1">
                                                                    Continue
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cart-grid-right col-xs-12 col-lg-3">
                                        <div class="cart-summary">
                                            <div class="cart-detailed-totals">
                                                <div class="cart-summary-products">
                                                    <div class="summary-label">There are 3 item in your cart</div>
                                                </div>
                                                <div class="cart-summary-line" id="cart-subtotal-products">
                                                    <span class="label js-subtotal">
                                                        Total products:
                                                    </span>
                                                    <span class="value">£200.00</span>
                                                </div>
                                                <div class="cart-summary-line" id="cart-subtotal-shipping">
                                                    <span class="label">
                                                        Total Shipping:
                                                    </span>
                                                    <span class="value">Free</span>
                                                    <div>
                                                        <small class="value"></small>
                                                    </div>
                                                </div>
                                                <div class="cart-summary-line cart-total">
                                                    <span class="label">Total:</span>
                                                    <span class="value">£200.00 (tax incl.)</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="block-reassurance">
                                            <ul>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check1.png' %}" alt="Security policy (edit with Customer reassurance module)">
                                                        <span>Security policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check2.png' %}" alt="Delivery policy (edit with Customer reassurance module)">
                                                        <span>Delivery policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div class="block-reassurance-item">
                                                        <img src="{% static 'img/product/check3.png' %}" alt="Return policy (edit with Customer reassurance module)">
                                                        <span>Return policy (edit with Customer reassurance module)</span>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}