blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import CheckoutView, order_create, order_history_view

app_name = 'orders'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('history/', order_history_view, name='history'),
    path('order/', order_create, name='order')
]

pages/urls.py
from django.urls import path

from pages.views import HomePageView, ContactTemplateView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
]

products/urls.py
from django.urls import path

from products.views import ProductsListView, ProductDetailView, add_or_remove, add_or_remove_likes, ProductCommentView

app_name = 'products'

urlpatterns = [
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('cart/<int:pk>/', add_or_remove, name='add-or-remove'),
    path('comment/<int:pk>/', ProductCommentView.as_view(), name='comment'),
    path('likes/<int:pk>/', add_or_remove_likes, name='add-or-remove-likes'),
    path('', ProductsListView.as_view(), name='list'),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('account/', AccountView.as_view(), name='account'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('change/password/', ChangePassword.as_view(), name='change-password'),
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    path('cart/', CartView.as_view(), name='cart'),
    path('verify/email/', verify_email, name='verify-email'),
]

users/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class VerificationCodeModel(models.Model):
    code = models.CharField(max_length=6, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='verification_codes')

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('Verification Code')
        verbose_name_plural = _('Verification Codes')


class AccountModel(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, related_name='account')
    full_name = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('full_name'))
    company = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('company'))
    city = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('city'))
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name=_('address'))
    postcode = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('phone'))
    country = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import AccountModel

User_model = get_user_model()


class RegisterForm(UserCreationForm):
    class Meta:
        model = User_model
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User_model.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')
        return email


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255)


class EmailVerificationForm(forms.Form):
    code = forms.CharField(max_length=6)


class AccountModelForm(forms.ModelForm):
    class Meta:
        model = AccountModel
        exclude = ('user',)

users/views.py
import pytz
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, FormView, UpdateView, ListView
from sympy import Product

from conf import settings
from products.models import ProductModel
from users.forms import RegisterForm, EmailVerificationForm, LoginForm, AccountModelForm
from users.models import VerificationCodeModel, AccountModel
import random

UserModel = get_user_model()


def send_email_verification(user):
    random_code = random.randint(100000, 999999)

    if VerificationCodeModel.objects.filter(code=random_code).exists():
        send_email_verification(user)

    else:
        VerificationCodeModel.objects.create(
            code=random_code,
            user=user
        )
        try:

            send_mail(
                'Verification Code',
                f'Your verification code is {random_code}',
                settings.EMAIL_HOST_USER, [user.email]
            )
            return True
        except Exception as e:
            return False


class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:verify-email')

    def form_valid(self, form):
        storage = messages.get_messages(self.request)
        storage.used = True
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        #send verification code
        send_email_verification(user)
        return super().form_valid(form)

    def form_invalid(self, form):
        storage = messages.get_messages(self.request)
        storage.used = True
        messages.error(self.request, form.errors)
        return self.render_to_response(self.get_context_data(form=form))


def verify_email(request):
    storage = messages.get_messages(request)
    storage.used = True
    if request.method == 'POST':
        form = EmailVerificationForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            user_code = VerificationCodeModel.objects.filter(code=code).first()
            if user_code:
                now = datetime.now(pytz.timezone(settings.TIME_ZONE))
                sent_time = user_code.created_at.astimezone(pytz.timezone(settings.TIME_ZONE)) + timedelta(minutes=2)
                if sent_time > now:
                    UserModel.objects.filter(pk=user_code.user.pk).update(is_active=True)
                    return redirect('users:login')

                else:
                    messages.error(request, 'Verification code is expired.')

            else:
                messages.error(request, 'This code is invalid')

        else:
            messages.error(request, form.errors)
    return render(request, 'users/verify-email.html')


class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('pages:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            return redirect(self.success_url)

        else:
            messages.error(self.request, 'Invalid username or password')

    def form_invalid(self, form):
        storage = messages.get_messages(self.request)
        storage.used = True
        messages.error(self.request, 'Form is invalid')

        return self.render_to_response(self.get_context_data(form=form))


def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect(reverse_lazy('pages:home'))


class AccountView(LoginRequiredMixin, UpdateView):
    template_name = 'users/acount.html'
    form_class = AccountModelForm
    success_url = reverse_lazy('users:account')
    context_object_name = 'account'
    login_url = reverse_lazy('users:login')

    def get_object(self, queryset=None):
        account, _ = AccountModel.objects.get_or_create(user=self.request.user)
        return account


class WishlistView(TemplateView):
    template_name = 'users/wishlist.html'


class CartView(ListView):
    template_name = 'users/cart.html'
    context_object_name = 'products'

    def get_queryset(self):
        cart = self.request.session.get('cart', [])
        products = ProductModel.objects.filter(pk__in=cart)
        return products

    def calculate_total_price(self):
        cart = self.request.session.get('cart', [])
        products = ProductModel.objects.filter(pk__in=cart)
        total_price = 0
        for product in products:
            total_price += product.get_price()
        return total_price

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = self.calculate_total_price()
        return context


class ChangePassword(TemplateView):
    template_name = 'users/reset-password.html'

templates/users/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="main-content" id="cart">
        <!-- main -->
        <div id="wrapper-site">
            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Shopping Cart</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <section id="main">
                            <div class="cart-grid row">
                                <div class="col-md-9 col-xs-12 check-info">
                                    <h1 class="title-page">Shopping Cart</h1>
                                    <div class="cart-container">
                                        <div class="cart-overview js-cart">
                                            <ul class="cart-items">
                                                {% for product in products %}
                                                <li class="cart-item">
                                                    <div class="product-line-grid row justify-content-between">
                                                        <!--  product left content: image-->
                                                        <div class="product-line-grid-left col-md-2">
                                                            <span class="product-image media-middle">
                                                                <a href="{% url 'products:detail' pk=product.id %}">
                                                                    <img class="img-fluid" src="{{ product.image1.url }}" alt="Organic Strawberry Fruits">
                                                                </a>
                                                            </span>
                                                        </div>
                                                        <div class="product-line-grid-body col-md-6">
                                                            <div class="product-line-info">
                                                                <a class="label" href="{% url 'products:detail' pk=product.id %}" data-id_customization="0">Organic Strawberry Fruits</a>
                                                            </div>
                                                            <div class="product-line-info product-price">
                                                                <span class="value">${{ product.get_price }}</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Size:</span>
                                                                <span class="value">S</span>
                                                            </div>
                                                            <div class="product-line-info">
                                                                <span class="label-atrr">Color:</span>
                                                                <span class="value">Blue</span>
                                                            </div>
                                                        </div>
                                                        <div class="product-line-grid-right text-center product-line-actions col-md-4">
                                                            <div class="row">
                                                                <div class="col-md-5 col qty">
                                                                    <div class="label">Qty:</div>
                                                                    <div class="quantity">
                                                                        <input type="text" name="qty" value="1" class="input-group form-control">

                                                                        <span class="input-group-btn-vertical">
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-up" type="button">
                                                                                +
                                                                            </button>
                                                                            <button class="btn btn-touchspin js-touchspin bootstrap-touchspin-down" type="button">
                                                                                -
                                                                            </button>
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-5 col price">
                                                                    <div class="label">Total:</div>
                                                                    <div class="product-price total">
                                                                        ${{ product.get_price }}
                                                                    </div>
                                                                </div>
                                                                <div class="col-md-2 col text-xs-right align-self-end">
                                                                    <div class="cart-line-product-actions ">
                                                                        <a class="remove-from-cart" rel="nofollow" href="{% url 'products:add-or-remove' pk=product.id %}?next={{ request.get_full_path|urlencode }}" data-link-action="delete-from-cart" data-id-product="1">
                                                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                                                        </a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                    <a href="{% url 'orders:checkout' %}" class="continue btn btn-primary pull-xs-right">
                                        Continue
                                    </a>
                                </div>
                                <div class="cart-grid-right col-xs-12 col-lg-3">
                                    <div class="cart-summary">
                                        <div class="cart-detailed-totals">
                                            <div class="cart-summary-products">
                                                <div class="summary-label">There are {{ products.count }} items in your cart</div>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-products">
                                                <span class="label js-subtotal">
                                                    Total price:
                                                </span>
                                                <span class="value">${{ total_price }}</span>
                                            </div>
                                            <div class="cart-summary-line" id="cart-subtotal-shipping">
                                                <span class="label">
                                                    Total Shipping:
                                                </span>
                                                <span class="value">Free</span>
                                                <div>
                                                    <small class="value"></small>
                                                </div>
                                            </div>
                                            <div class="cart-summary-line cart-total">
                                                <span class="label">Total:</span>
                                                <span class="value">£200.00 (tax incl.)</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="block-reassurance">
                                        <ul>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check1.png' %}" alt="Security policy (edit with Customer reassurance module)">
                                                    <span>Security policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check2.png' %}" alt="Delivery policy (edit with Customer reassurance module)">
                                                    <span>Delivery policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="block-reassurance-item">
                                                    <img src="{% static 'img/product/check3.png' %}" alt="Return policy (edit with Customer reassurance module)">
                                                    <span>Return policy (edit with Customer reassurance module)</span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'pages:home' %}">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">
                                    <span>Login</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div id="content-wrapper" class="full-width">
                <div id="main">
                    <div class="container">
                        <h1 class="text-center title-page">Log In</h1>
                        <div class="login-form">
                            <form id="customer-form" action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div>
                                    <input type="hidden" name="back" value="my-account">
                                    <div class="form-group no-gutters">
                                        <input class="form-control" name="username" type="text" placeholder=" Email">
                                    </div>
                                    <div class="form-group no-gutters">
                                        <div class="input-group js-parent-focus">
                                            <input class="form-control js-child-focus js-visible-password" name="password" type="password" value="" placeholder="Password">
                                        </div>
                                    </div>
                                    <div class="no-gutters text-center">
                                        <div class="forgot-password">
                                            <a href="reset-password.html" rel="nofollow">
                                                Forgot your password?
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix">
                                    <div class="text-center no-gutters">
                                        <input type="hidden" name="submitLogin" value="1">
                                        <button class="btn btn-primary" data-link-action="sign-in" type="submit">
                                            Sign in
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/order-history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="main-content">
        <div class="wrap-banner">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="{% url 'pages:home' %}">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'orders:history' %}">
                                    <span>Orders History</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>

        </div>

        <!-- main -->
        <div id="wrapper-site">
            <div class="container">
                <div class="row">
                    <div id="content-wrapper" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 onecol">
                        <div id="main">
                            <div id="content" class="page-content">
                                <div id="mywishlist">
                                    <h1 class="title-page">My Orders</h1>
                                    <form method="post" class="std" id="customer-form">
                                        <fieldset>
                                            <h3>Search order</h3>
                                            <div class="input-group">
                                                <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="">
                                                <button class="btn" type="submit" data-action="show-password" data-text-show="Show" data-text-hide="Hide">
                                                    Save
                                                </button>
                                            </div>
                                        </fieldset>
                                    </form>
                                    <div id="block-history" class="block-center">
                                        <table class="std table">
                                            <thead>
                                                <tr>
                                                    <th class="first_item">Order ID</th>
                                                    <th class="item mywishlist_first">Qty</th>
                                                    <th class="item mywishlist_second">Created</th>
                                                    <th class="item mywishlist_second">Direct Link</th>
                                                    <th class="item mywishlist_second">Status</th>
                                                    <th class="last_item mywishlist_first">Delete</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for order in orders %}
                                                <tr id="wishlist_1">
                                                    <td>
                                                        <a href="javascript:;" onclick="javascript:WishlistManage('block-order-detail', '1');">#{{ order.id }}</a>
                                                    </td>
                                                    <td class="bold align_center">
                                                        {{ order.items.count }}
                                                    </td>
                                                    <td>{{ order.created_at|date }}</td>
                                                    <td>
                                                        <a href="javascript:;" onclick="javascript:WishlistManage('block-order-detail', '1');">View</a>
                                                    </td>
                                                    <td class="wishlist_default">
                                                        <p class="is_wish_list_default">
                                                            {% if order.status %}
                                                                Accepted
                                                            {% else %}
                                                                Pending
                                                            {% endif %}
                                                        </p>
                                                    </td>
                                                    <td class="wishlist_delete">
                                                        <a href="javascript:;" onclick="return (WishlistDelete('wishlist_1', '1', 'Do you really want to delete this wishlist ?'));">Delete</a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="page-home">
                                        <a class="btn btn-default" href="index-2.html">
                                            <i class="fa fa-home" aria-hidden="true"></i>
                                            <span>Homepage</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}